### ISSUE TITLE
Generate daily BRAN2020 output for EAC mooring

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [shared-climate-data-problems/BRAN-reanalysis#2]
Let's grab daily output that covers the time period, Jan 2010- Dec 2022 of the EAC moorings. Variables would be u, v, T, S from surface to ~1500 m. The time stamp required is 0000Z for each day.  
 
location of the EAC mooring array on BRAN2020 grid is:
```
% BRAN EAC lat -29.0 = 460, -26 = 490, -27.1 = 478
% BRAN EAC lon 153.5 = 1535, 155.2 = 1552
```

**Comment by Thomas-Moore-Creative** [comment]
[About the EAC mooring array dataset](https://oceancurrent.aodn.org.au/eac.php)](https://oceancurrent.aodn.org.au/eac.php)

**Comment by Thomas-Moore-Creative** [comment]
@BSloyan here is the data slice I plan to save out as `NetCDF`.  The closest native `latitude` is -26.95.  Note this is `temperature` and the `u` & `v` will be at something like -27.0 on the grid faces.
![CleanShot 2024-07-29 at 13 27 06@2x](https://github.com/user-attachments/assets/21bef14d-8b10-40d8-8e5f-ea33cdcde629)
![CleanShot 2024-07-29 at 13 26 40@2x](https://github.com/user-attachments/assets/d5e1fb0c-7471-4998-8012-821b8ee35752)

**Comment by Thomas-Moore-Creative** [comment]
@BSloyan NetCDF files:
```
(base) tm4888@gadi-login-04 /g/data/es60/users/thomas_moore/EAC_BRAN_slices ls -ltrh *.nc
-rw-r--r-- 1 tm4888 es60 28M Jul 29 13:56 EAC_mooring_BRAN2020_uv.nc
-rw-r--r-- 1 tm4888 es60 26M Jul 29 14:00 EAC_mooring_BRAN2020_ts.nc
```

Copied to local Tube machine.  See email for details.

Some interesting features when you animate the N/S and E/W currents together across time.
![CleanShot 2024-07-31 at 13 37 46@2x](https://github.com/user-attachments/assets/0878ecf0-22c9-400a-bf47-d77122050003)

**Comment by BSloyan** [comment]
Thanks,
